import Link from 'next/link'
import { notFound } from 'next/navigation'
import SiteHeader from '@/components/site-header'
import SiteFooter from '@/components/site-footer'
import PageHero from '@/components/page-hero'
import { jurisdictions } from '@/lib/content'
import { ArrowRight } from 'lucide-react'
export function generateStaticParams(){return jurisdictions.map(j=>({slug:j.slug}))}
export default async function JurisdictionPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const j=jurisdictions.find(x=>x.slug===slug);if(!j)notFound();return <><SiteHeader/><main><PageHero eyebrow={'Jurisdiction · '+j.label} title={<>India entry for <em>{j.name} companies.</em></>}><p>{j.description} This guide is designed to help a parent company understand the decisions before engaging on incorporation or ongoing support.</p></PageHero><section className="article-layout section"><article className="article-body"><div className="quick-answer"><strong>Quick view</strong><p>The right Indian presence depends on the proposed activities, ownership, funding route, sector, people model and expected scale. A structure should be selected after those factors are mapped.</p></div><h2>Start with the business objective</h2><p>Define why the Indian operation is being created: market development, local revenue, engineering, shared services, sourcing, manufacturing, investment or another purpose. The objective affects the structure and the compliance path.</p><h2>Choose the Indian presence</h2><div className="comparison-table"><div><strong>Wholly owned subsidiary</strong><span>Separate Indian company with broader operating flexibility.</span></div><div><strong>Branch office</strong><span>An extension of the foreign parent, subject to permitted activities and applicable approvals.</span></div><div><strong>Liaison office</strong><span>Generally suited to representative and liaison activities rather than commercial operations.</span></div></div><h2>Plan the compliance architecture</h2>{['FDI and FEMA considerations','Corporate and tax registrations','Accounting and reporting','Payroll and employment compliance','Transfer pricing and cross-border transactions'].map((x,i)=><div className="article-section" key={x}><span className="section-index">0{i+1}</span><div><h3>{x}</h3><p>The requirement should be considered as part of the overall operating model rather than treated as a separate filing exercise.</p></div></div>)}<h2>Next step</h2><p>Once the objective and structure are clear, the work can move into incorporation, registrations, banking, finance and the ongoing compliance calendar.</p><Link href="/#contact" className="button button-gold">Discuss your India plans <ArrowRight size={16}/></Link></article><aside className="inquiry-card"><p className="eyebrow gold">India entry desk</p><h3>Need to compare your options?</h3><p>We can map the main India workstreams before you commit to a structure.</p><Link href="/#contact" className="button button-gold">Send an enquiry <ArrowRight size={16}/></Link></aside></section></main><SiteFooter/></>}
