import Link from 'next/link'
import SiteHeader from '@/components/site-header'
import SiteFooter from '@/components/site-footer'
import { ArrowRight } from 'lucide-react'
import { services, jurisdictions, articles } from '@/lib/content'

export default function HomePage(){
 return <><SiteHeader/><main>
  <section className="hero" id="top"><div className="hero-content"><p className="eyebrow gold">India entry & business advisory</p><h1>Build your India presence with <em>clarity.</em></h1><p className="hero-copy">AU Corporate helps international and Indian businesses make considered decisions across India entry, business structure, tax, finance, payroll and ongoing compliance.</p><Link href="/india-entry" className="button button-gold">Explore India entry <ArrowRight size={16}/></Link></div><div className="hero-mark" aria-hidden="true"><div className="mark-ring ring-one"/><div className="mark-ring ring-two"/><span>AU</span></div><div className="hero-bottom"><span>Understand · Establish · Operate · Grow</span><span>India-focused advisory</span></div></section>

  <section className="section"><div className="section-heading"><p className="eyebrow">The India lifecycle</p><h2>One connected view from <em>entry to operation.</em></h2><p className="section-intro">The decisions made before incorporation often shape tax, funding, people, reporting and compliance long afterwards. We organise the work around that lifecycle.</p></div><div className="lifecycle-grid">{['Understand the objective','Choose the structure','Establish the presence','Get compliant','Operate, grow or exit'].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>Practical guidance for the decision at this stage.</p></div>)}</div></section>

  <section className="section services-section" id="services"><div className="section-heading"><p className="eyebrow">The practice</p><h2>Relevant specialists for <em>the decisions ahead.</em></h2></div><div className="service-grid">{services.slice(0,6).map(s=><article className="service-card" key={s.slug}><span className="card-number">{s.number}</span><div><h3>{s.title}</h3><p>{s.summary}</p><Link href={'/services/'+s.slug} className="text-link">Explore practice <ArrowRight size={15}/></Link></div></article>)}</div></section>

  <section className="jurisdiction-strip"><div><p className="eyebrow gold">Jurisdiction-specific guidance</p><h2>Your India structure should reflect <em>where you come from.</em></h2><p>Our most developed country journey is USA → India, supported by dedicated guides for other major markets.</p></div><div className="jurisdiction-mini">{jurisdictions.map(j=><Link key={j.slug} href={'/india-entry/'+j.slug}>{j.label}<ArrowRight size={14}/></Link>)}</div></section>

  <section className="approach-section" id="approach"><div className="approach-inner"><div><p className="eyebrow gold">Our approach</p><h2>Understand first.<br/><em>Then build.</em></h2></div><div className="approach-copy"><p>We start with the commercial objective and connect the relevant Indian structure, regulatory, tax, finance and people considerations into one practical work plan.</p><Link href="/about" className="button button-light">The firm <ArrowRight size={16}/></Link></div></div><div className="approach-rule"/><div className="principles"><span>01 / Diagnose</span><span>02 / Establish</span><span>03 / Operationalise</span><span>04 / Execute</span><span>05 / Partner</span></div></section>

  <section className="section insights-section" id="insights"><div className="insights-top"><div><p className="eyebrow">Knowledge & insights</p><h2>Useful thinking for <em>India operations.</em></h2></div><Link href="/insights" className="text-link">View all insights <ArrowRight size={15}/></Link></div><div className="insight-grid">{articles.map((a,i)=><article className={i===0?'insight-card featured':'insight-card'} key={a.slug}><div className="insight-visual"><span>AU / {String(i+1).padStart(2,'0')}</span></div><p className="insight-category">{a.category} <span>· {a.read}</span></p><h3>{a.title}</h3><Link href={'/insights/'+a.slug} className="text-link">Read article <ArrowRight size={15}/></Link></article>)}</div></section>

  <section className="contact-section" id="contact"><div><p className="eyebrow gold">Start a conversation</p><h2>Let's make the <em>next step clear.</em></h2><p className="contact-note">Tell us what you are planning in India. We can help identify the relevant workstreams and where to start.</p></div><div className="contact-actions"><Link href="/india-entry" className="button button-gold">Explore India entry <ArrowRight size={16}/></Link><p>For a specific question, contact AU Corporate and we will direct it to the appropriate team.</p></div></section>
 </main><SiteFooter/></>
}