export type Service = { slug:string; number:string; title:string; summary:string; bestFor:string[]; sections:string[]; };
export const services: Service[] = [
 {slug:"india-entry",number:"01",title:"India entry & business setup",summary:"A structured route from deciding to enter India to establishing an operating presence.",bestFor:["Foreign companies entering India","International groups building an India team","Businesses evaluating the right Indian structure"],sections:["Choosing an India presence","Incorporation and registrations","Banking and operational setup","First-year compliance"]},
 {slug:"fdi-fema",number:"02",title:"FDI, FEMA & RBI compliance",summary:"Practical support for foreign investment, reporting, capital flows and cross-border obligations.",bestFor:["Foreign-owned Indian companies","Parent companies funding India operations","Businesses managing cross-border transactions"],sections:["FDI route and structure","RBI reporting","Capital and share transactions","Ongoing FEMA compliance"]},
 {slug:"tax-regulatory",number:"03",title:"Tax & regulatory advisory",summary:"Connected Indian tax and regulatory guidance for businesses operating across jurisdictions.",bestFor:["India subsidiaries and branches","Cross-border service arrangements","Businesses managing recurring tax obligations"],sections:["Corporate income tax","GST and indirect tax","TDS and withholding","DTAA and cross-border considerations"]},
 {slug:"accounting-assurance",number:"04",title:"Accounting & assurance",summary:"Accounting, reporting and assurance support that keeps India operations useful to management and aligned with group requirements.",bestFor:["Foreign-owned Indian entities","India finance teams","Groups requiring parent reporting"],sections:["Monthly accounting","Management reporting","Statutory audit support","Group reporting"]},
 {slug:"payroll-hr",number:"05",title:"Payroll & HR compliance",summary:"Practical payroll and employment compliance support for teams operating in India.",bestFor:["New India teams","Growing subsidiaries","International businesses hiring locally"],sections:["Payroll processing","Statutory deductions","Employment compliance","HR administration"]},
 {slug:"transfer-pricing",number:"06",title:"Transfer pricing",summary:"Documentation and advisory for related-party transactions between India and overseas group entities.",bestFor:["India subsidiaries","Shared-service arrangements","Cross-border group transactions"],sections:["Transaction review","Benchmarking","Documentation","Ongoing compliance"]},
];
export const jurisdictions = [
 {slug:"usa",name:"United States",label:"USA → India",description:"A focused guide for US companies establishing, funding and operating an Indian presence."},
 {slug:"uk",name:"United Kingdom",label:"UK → India",description:"Practical India-entry guidance for UK businesses and groups."},
 {slug:"singapore",name:"Singapore",label:"Singapore → India",description:"India-entry and cross-border considerations for Singapore-based businesses."},
 {slug:"germany",name:"Germany",label:"Germany → India",description:"India setup, tax and compliance considerations for German businesses."},
 {slug:"japan",name:"Japan",label:"Japan → India",description:"A practical route for Japanese companies building India operations."},
 {slug:"australia",name:"Australia",label:"Australia → India",description:"India-entry considerations for Australian companies and founders."},
 {slug:"china",name:"China",label:"China → India",description:"India market-entry and compliance considerations for Chinese businesses."},
];
export const articles = [
 {slug:"how-to-choose-india-business-structure",category:"India Entry",title:"How to choose the right business structure for India",excerpt:"A practical framework for foreign companies comparing a subsidiary, branch office, liaison office and other routes into India.",updated:"7 October 2026",read:"9 min read",headings:["Start with the commercial objective","Compare the available structures","Consider tax and regulatory consequences","Plan the operating model","Review the decision before incorporation"]},
 {slug:"india-compliance-after-incorporation",category:"Compliance",title:"What happens after an Indian company is incorporated?",excerpt:"Incorporation is the beginning of the operating cycle. Here is how foreign-owned businesses can organise the first compliance and finance steps.",updated:"7 October 2026",read:"8 min read",headings:["The first operating priorities","Tax and GST registrations","Accounting and payroll","Corporate and FEMA compliance","Building the annual calendar"]},
 {slug:"us-company-entering-india",category:"United States → India",title:"A practical starting point for a US company entering India",excerpt:"The decisions that usually matter before a US parent commits to an Indian operating structure.",updated:"7 October 2026",read:"10 min read",headings:["Clarify the India objective","Choose the legal presence","Prepare the parent documentation","Plan tax and FEMA obligations","Move from setup to operations"]},
];
