import Link from 'next/link'
import { notFound } from 'next/navigation'
import SiteHeader from '@/components/site-header'
import SiteFooter from '@/components/site-footer'
import { getPublishedArticle } from '@/lib/articles'
import { ArrowRight } from 'lucide-react'

export const dynamic = 'force-dynamic'

export default async function InsightPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params
  const a:any=await getPublishedArticle(slug)
  if(!a)notFound()
  const sections=a.content?.sections?.length ? a.content.sections : (a.headings??[]).map((h:string)=>({heading:h,paragraphs:['For businesses considering India, this is where the practical detail matters. The decision should be assessed against the intended activities, ownership, funding, people, reporting requirements and longer-term operating model.','AU Corporate connects the relevant Indian requirements into an actionable work plan while keeping the commercial objective in view.']}))
  const faqs=a.content?.faqs?.length ? a.content.faqs : [{question:'What should be decided before incorporation?',answer:'The appropriate structure depends on the business objective, activities, ownership, funding and expected operating model.'},{question:'How early should compliance be planned?',answer:'Compliance should be considered before incorporation so that the operating model and recurring obligations are planned together.'}]
  const category=a.category?.name ?? a.category ?? 'Insights'
  const updated=a.updatedAt ? new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(new Date(a.updatedAt)) : a.updated
  return <><SiteHeader/><main><div className="article-hero"><div className="article-hero-inner"><p className="eyebrow gold">{category}</p><h1>{a.title}</h1><p className="article-excerpt">{a.excerpt}</p><div className="article-meta"><span>{a.author?.name ?? 'AU Corporate'}</span><span>Updated {updated}</span><span>{a.readingTime ? a.readingTime+' min read' : a.read}</span></div></div></div><section className="article-layout section"><article className="article-body"><div className="toc"><strong>Contents</strong><ol>{sections.map((s:any,i:number)=><li key={s.heading}><a href={'#section-'+i}>{s.heading}</a></li>)}</ol></div><p className="lead">{a.excerpt}</p>{sections.map((s:any,i:number)=><section className="article-section prose-section" id={'section-'+i} key={s.heading}><span className="section-index">{String(i+1).padStart(2,'0')}</span><div><h2>{s.heading}</h2>{(s.paragraphs??[]).map((p:string,j:number)=><p key={j}>{p}</p>)}{s.callout&&<div className="callout"><strong>{s.callout.title}</strong><p>{s.callout.text}</p></div>}</div></section>)}<h2>Frequently asked questions</h2><div className="faq-list">{faqs.map((f:any)=><details key={f.question}><summary>{f.question}</summary><p>{f.answer}</p></details>)}</div><div className="author-block"><strong>{a.author?.name ?? 'AU Corporate'}</strong><p>{a.author?.bio ?? 'India-focused business advisory across market entry, structure, tax, finance and compliance.'}</p></div></article><aside className="inquiry-card sticky-card"><p className="eyebrow gold">Discuss your India plans</p><h3>Need help applying this to your business?</h3><p>Share your question and we can point you to the relevant India workstream.</p><Link href="/#contact" className="button button-gold">Send an enquiry <ArrowRight size={16}/></Link><div className="aside-links"><strong>Related</strong><Link href="/india-entry">India entry</Link><Link href="/services">Our practice</Link><Link href="/insights">More insights</Link></div></aside></section></main><SiteFooter/></>}
